#:kivy 2.0.0

#a widget -> enclosed in <>
# main program uses kv file to get info about wigdet obj in program
<Game2048>
  canvas.before:
    Color:
      rgba: (1,1,1,0)
    Rectangle:
      pos: self.pos
      size: self.size


  #a child widget
  Label:

    #proerties of widget to indicate what will appear on screen
    font_size: 50
    text: "John Bonds III"
    center_x: root.width / 2
    top: root.top / 2
  #
  # canvas:
  #     Rectangle:
  #       pos: 5
  #       size: 5
